language: julia
os:
    - osx
    - linux
julia:
    - 0.7
    - nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("Colors"); Pkg.test("Colors"; coverage=true)';
jobs:
  include:
    - stage: deploy
      julia: 0.7
      os: linux
      script:
        - julia -e 'Pkg.clone(pwd()); Pkg.build("Colors")'
        - julia -e 'Pkg.add("Documenter")'
        - julia -e 'cd(Pkg.dir("Colors")); include("docs/make.jl")'
after_success:
    - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'cd(Pkg.dir("Colors")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'; fi
