language: julia
os:
    - osx
    - linux
julia:
    - 0.7
    - nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("Colors"); Pkg.test("Colors"; coverage=true)';
jobs:
  include:
    - stage: deploy
      julia: 0.7
      os: linux
      script:
        - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("Colors")'
        - julia -e 'using Pkg; Pkg.add("Documenter")'
        - julia -e 'import Colors; cd(joinpath(pathof(Colors),"..","..")); include("docs/make.jl")'
after_success:
    - julia -e 'using Pkg; import Colors; cd(joinpath(pathof(Colors),"..","..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
